bot_credentials:
  id: 1111111111
  username: PLACE_YOUR_USERNAME_BOT
  secret: 1111111111:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

timezone: 'Europe/Moscow'

superusers:
  - 11111111

responsible_persons:
  - 11111111
  - 222222222

groups:
  main:
    id: -1001111111111
    public_link: https://t.me/YOUR_PUBLIC_GROUP_LINK
  chat:
    id: -1001222222222

messages_templates:
  pin_message: ""
  pin_message_button: 🚨 Сообщить
  request: "*{type}*\n\n
*Где:* {area}\n
*Адрес:* {address}\n
*Сообщил:* {username}\n
*Детали:* {description}\n\n
Сообщить о проблеме 👉 @PLACE\\_YOUR\\_USERNAME\\_BOT"
  request_fire_hint:
    "Охрана проверит ваш подъезд на предмет задымления и сообщит если что-то обнаружила. Охрана не отключает пожарную сигнализацию, для этого вам необходимо создать заявку на отключение в приложении или позвонить по номеру 8-888-888-88-88."
  success:
    "Готово\\! Ваша заявка зарегистрирована:\n{message_link}"
  ad_message:
    "👮 Чтобы прозрачно видеть все заявки, поступающие в охрану, Вы можете подписаться на канал охраны:\n
    {channel_link}
    \n\n
    ⭐️ Расскажите соседям в своем домовом чате об этом боте, отправьте им ссылку на него:\n
    {bot_link}"
  bad_words_fallback:
    Простите, но в вашем сообщениии недопустимые слова. Отправьте сообщение заново устранив нарушения.
  fallback:
    Простите, но я не знаю что на это ответить. Если что-то идет не так, напишите "начать сначала"
  welcome:
    Привет! Я бот охраны и я помогу создать Вам новую заявку
  start:
    Выберите ниже что у вас случилось
  select_street:
    Какая у Вас улица?
  select_house_number:
    Какой у Вас номер дома?
  select_problem_area:
    Где произошла проблема?
  select_section_number:
    Какой Ваш номер секции (подъезда)?
  select_floor_number:
    На каком этаже проблема (номер)?
  select_flat_number:
    Рядом с какой квартирой проблема?
  select_storeroom_number:
    Рядом с какой кладовкой проблема?
  select_parking_number:
    Рядом с каким парковочным местом проблема?
  specify_description:
    Уточните детали по Вашей проблеме, которые нужно знать охране
  confirm_request:
    Почти готово. Проверьте правильность данных и подтвердите отправку. Если что-то неверно, Вы можете вернуться назад или начать сначала.
  upload_photo:
    Отправьте в этот диалог фото или видео чтобы прикрепить его к проблеме
  confirm_suspect_object:
    Вы обнаружили объект, похожий на сверток/коробку/пакет, который может представлять опасность для окружающих?
  found_object_redirect:
    По всем потерянным или найденным вещам, не представляющим опасность, обратитесь в чат вашего дома, а также в чат находок
  rules: "
Если у вас что-то случилось, нажмите кнопку \"Сообщить\" в закрепленной шапке канала, запустите бота, заполните и отправьте заявку, она автоматически опубликуются в данном канале и охрана примет вашу заявку в работу. Если охрана даст ответ на заявку, бот оповестит вас об этом в личные сообщения.\n
При вводе информации заявки постарайтесь как можно точнее внести где и что случилось. Если у вас есть фото или видео случившегося, не забудьте их прикрепить.\n
\n
Краткая информация и правила канала:\n
- данный канал создан инициативными жителями и никак не связан с управляющей компанией\n
- канал служит для оперативной передачи информации об инциденте в ЧОП\n
- это публичное пространство, пожалуйста, уважительно относитесь ко всем его участникам, не грубите и не переходите на личности\n
- не размещайте на всеобщее обозрение свою или чужую персональную информацию\n
- все вопросы по качеству услуг и регламенту работы необходимо направлять напрямую в УК\n
- здесь нельзя запросить видео с камер, это делается только через запрос в УК\n
- за мат и оскорбления других участников - предупреждение, за повторное - бан\n
- за публикацию оскорбительных или непристойного содержания фото или видео - бан\n
- за использование бота для распространения спама, а также размещение любой другой информации не имеющей отношения к вызову охраны на место инцидента, в том числе любые обсуждения, оценки, бессмысленный текст сообщения - предупреждение, за повторное - бан\n
- в случае подозрений на регулярные недобросовестные вызовы охраны без реальных происшествий - предупреждение, за повторное бан\n
- блокировка может быть выдана на определенный срок или навсегда в случае непрекращающихся злостных нарушений\n
- в случае блокировки вы всегда можете воспользоваться любыми другими официальными способами связи с охраной, в том числе приложением\n
"
  contacts: "
С охраной можно срочно связаться:\n
- Написать в Telegram @XXXXXXXX\n
- Позвонить по номеру телефона +77777777777
"
  received_response_from_responsible_person:
    "На вашу заявку получен ответ от охраны:\n"
  request_already_exists:
    "Ваш запрос уже был отправлен кем-то еще:"
  access_restricted:
    Доступ ограничен


keyphrases:
  go_back:
    - назад
    - взад
    - вернуться
    - обратно
    - прошл
  go_restart:
    - начат
    - начало
    - отмен
    - сброс
  go_confirm:
    - 'ok'
    - 'yes'
    - '+'
    - ок
    - да
    - подтвержд
    - отправ
    - хорош
    - правил
  issues_categories:
    - Пожарная сигнализация
    - Подозрительная личность
    - Порча имущества
    - Нарушение правопорядка
    - Шумные работы/компания
    - Потеряна/найдена вещь
    - Другое
  special_buttons:
    - Правила
    - Контакты
  supported_streets:
    - улица Пушкина
    - проспект Мира
  problem_areas:
    - На этаже
    - У квартиры
    - На паркинге
    - В кладовках
    - Во внутреннем дворе
    - На улице у дома
  control_buttons:
    - Назад
    - Начать сначала
  confirmation:
    - Отправить заявку
    - Изменить описание
    - Изменить фото/видео

streets:
  - name: улица Пушкина
    buildings:
      - number: 1
        enabled: True
        floors_per_section:
          - 9
          - 15
      - number: 2
        enabled: True
        floors_per_section:
          - 5
          - 5
          - 5

bad_words:
 - жопа
 - лох
