version: '3'
services:
  oxpaha28_bot:
    image: ghcr.io/ileonidze/oxpaha28_bot:latest
    container_name: oxpaha28_bot
    restart: unless-stopped
    volumes:
      - ./config.yaml:/opt/bot/config.yaml
      - ./context.yaml:/opt/bot/context.yaml
